# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tetris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tetris.proto',
  package='tetris',
  serialized_pb=_b('\n\x0ctetris.proto\x12\x06tetris\"/\n\tHandshake\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\r\x12\x11\n\tstreamKey\x18\x02 \x02(\t\"\x0e\n\x0cHandshakeACK\"\xb5\x03\n\x06Report\x12\x0e\n\x06quorum\x18\x01 \x02(\r\x12\x11\n\tconnected\x18\x02 \x02(\r\x12\x0c\n\x04time\x18\x03 \x02(\r\x12-\n\x08joystick\x18\x04 \x03(\x0b\x32\x1b.tetris.Report.JoystickInfo\x12+\n\x07tactile\x18\x05 \x03(\x0b\x32\x1a.tetris.Report.TactileInfo\x1a|\n\x04Info\x12\x11\n\tfrequency\x18\x01 \x01(\x01\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12\r\n\x05stdev\x18\x03 \x01(\x01\x12\x15\n\rupperQuartile\x18\x04 \x01(\x01\x12\x15\n\rlowerQuartile\x18\x05 \x01(\x01\x12\x16\n\x0enormalizedMean\x18\x06 \x01(\x01\x1a?\n\x0cJoystickInfo\x12\x0c\n\x04\x61xis\x18\x01 \x02(\r\x12!\n\x04info\x18\x02 \x02(\x0b\x32\x13.tetris.Report.Info\x1a_\n\x0bTactileInfo\x12\x0c\n\x04\x63ode\x18\x01 \x02(\r\x12\x1f\n\x02up\x18\x02 \x01(\x0b\x32\x13.tetris.Report.Info\x12!\n\x04\x64own\x18\x03 \x01(\x0b\x32\x13.tetris.Report.Info\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x02(\t\"\xf6\x01\n\x0eProgressUpdate\x12\x31\n\x08progress\x18\x01 \x03(\x0b\x32\x1f.tetris.ProgressUpdate.Progress\x1a\xb0\x01\n\x08Progress\x12:\n\x06target\x18\x01 \x02(\x0e\x32*.tetris.ProgressUpdate.Progress.TargetType\x12\x0c\n\x04\x63ode\x18\x02 \x02(\r\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x10\n\x08\x63ooldown\x18\x04 \x01(\r\x12\r\n\x05\x66ired\x18\x05 \x01(\x08\"\'\n\nTargetType\x12\x0b\n\x07TACTILE\x10\x00\x12\x0c\n\x08JOYSTICK\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROGRESSUPDATE_PROGRESS_TARGETTYPE = _descriptor.EnumDescriptor(
  name='TargetType',
  full_name='tetris.ProgressUpdate.Progress.TargetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TACTILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOYSTICK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=763,
  serialized_end=802,
)
_sym_db.RegisterEnumDescriptor(_PROGRESSUPDATE_PROGRESS_TARGETTYPE)


_HANDSHAKE = _descriptor.Descriptor(
  name='Handshake',
  full_name='tetris.Handshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='tetris.Handshake.channel', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='streamKey', full_name='tetris.Handshake.streamKey', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=71,
)


_HANDSHAKEACK = _descriptor.Descriptor(
  name='HandshakeACK',
  full_name='tetris.HandshakeACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=87,
)


_REPORT_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='tetris.Report.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='tetris.Report.Info.frequency', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean', full_name='tetris.Report.Info.mean', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stdev', full_name='tetris.Report.Info.stdev', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upperQuartile', full_name='tetris.Report.Info.upperQuartile', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowerQuartile', full_name='tetris.Report.Info.lowerQuartile', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalizedMean', full_name='tetris.Report.Info.normalizedMean', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=365,
)

_REPORT_JOYSTICKINFO = _descriptor.Descriptor(
  name='JoystickInfo',
  full_name='tetris.Report.JoystickInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis', full_name='tetris.Report.JoystickInfo.axis', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='tetris.Report.JoystickInfo.info', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=430,
)

_REPORT_TACTILEINFO = _descriptor.Descriptor(
  name='TactileInfo',
  full_name='tetris.Report.TactileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tetris.Report.TactileInfo.code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='up', full_name='tetris.Report.TactileInfo.up', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='down', full_name='tetris.Report.TactileInfo.down', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=527,
)

_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='tetris.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quorum', full_name='tetris.Report.quorum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connected', full_name='tetris.Report.connected', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='tetris.Report.time', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joystick', full_name='tetris.Report.joystick', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tactile', full_name='tetris.Report.tactile', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REPORT_INFO, _REPORT_JOYSTICKINFO, _REPORT_TACTILEINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=527,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='tetris.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tetris.Error.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=553,
)


_PROGRESSUPDATE_PROGRESS = _descriptor.Descriptor(
  name='Progress',
  full_name='tetris.ProgressUpdate.Progress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='tetris.ProgressUpdate.Progress.target', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='tetris.ProgressUpdate.Progress.code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='tetris.ProgressUpdate.Progress.progress', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cooldown', full_name='tetris.ProgressUpdate.Progress.cooldown', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fired', full_name='tetris.ProgressUpdate.Progress.fired', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROGRESSUPDATE_PROGRESS_TARGETTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=802,
)

_PROGRESSUPDATE = _descriptor.Descriptor(
  name='ProgressUpdate',
  full_name='tetris.ProgressUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='tetris.ProgressUpdate.progress', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROGRESSUPDATE_PROGRESS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=802,
)

_REPORT_INFO.containing_type = _REPORT
_REPORT_JOYSTICKINFO.fields_by_name['info'].message_type = _REPORT_INFO
_REPORT_JOYSTICKINFO.containing_type = _REPORT
_REPORT_TACTILEINFO.fields_by_name['up'].message_type = _REPORT_INFO
_REPORT_TACTILEINFO.fields_by_name['down'].message_type = _REPORT_INFO
_REPORT_TACTILEINFO.containing_type = _REPORT
_REPORT.fields_by_name['joystick'].message_type = _REPORT_JOYSTICKINFO
_REPORT.fields_by_name['tactile'].message_type = _REPORT_TACTILEINFO
_PROGRESSUPDATE_PROGRESS.fields_by_name['target'].enum_type = _PROGRESSUPDATE_PROGRESS_TARGETTYPE
_PROGRESSUPDATE_PROGRESS.containing_type = _PROGRESSUPDATE
_PROGRESSUPDATE_PROGRESS_TARGETTYPE.containing_type = _PROGRESSUPDATE_PROGRESS
_PROGRESSUPDATE.fields_by_name['progress'].message_type = _PROGRESSUPDATE_PROGRESS
DESCRIPTOR.message_types_by_name['Handshake'] = _HANDSHAKE
DESCRIPTOR.message_types_by_name['HandshakeACK'] = _HANDSHAKEACK
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['ProgressUpdate'] = _PROGRESSUPDATE

Handshake = _reflection.GeneratedProtocolMessageType('Handshake', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKE,
  __module__ = 'tetris_pb2'
  # @@protoc_insertion_point(class_scope:tetris.Handshake)
  ))
_sym_db.RegisterMessage(Handshake)

HandshakeACK = _reflection.GeneratedProtocolMessageType('HandshakeACK', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKEACK,
  __module__ = 'tetris_pb2'
  # @@protoc_insertion_point(class_scope:tetris.HandshakeACK)
  ))
_sym_db.RegisterMessage(HandshakeACK)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), dict(

  Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_INFO,
    __module__ = 'tetris_pb2'
    # @@protoc_insertion_point(class_scope:tetris.Report.Info)
    ))
  ,

  JoystickInfo = _reflection.GeneratedProtocolMessageType('JoystickInfo', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_JOYSTICKINFO,
    __module__ = 'tetris_pb2'
    # @@protoc_insertion_point(class_scope:tetris.Report.JoystickInfo)
    ))
  ,

  TactileInfo = _reflection.GeneratedProtocolMessageType('TactileInfo', (_message.Message,), dict(
    DESCRIPTOR = _REPORT_TACTILEINFO,
    __module__ = 'tetris_pb2'
    # @@protoc_insertion_point(class_scope:tetris.Report.TactileInfo)
    ))
  ,
  DESCRIPTOR = _REPORT,
  __module__ = 'tetris_pb2'
  # @@protoc_insertion_point(class_scope:tetris.Report)
  ))
_sym_db.RegisterMessage(Report)
_sym_db.RegisterMessage(Report.Info)
_sym_db.RegisterMessage(Report.JoystickInfo)
_sym_db.RegisterMessage(Report.TactileInfo)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'tetris_pb2'
  # @@protoc_insertion_point(class_scope:tetris.Error)
  ))
_sym_db.RegisterMessage(Error)

ProgressUpdate = _reflection.GeneratedProtocolMessageType('ProgressUpdate', (_message.Message,), dict(

  Progress = _reflection.GeneratedProtocolMessageType('Progress', (_message.Message,), dict(
    DESCRIPTOR = _PROGRESSUPDATE_PROGRESS,
    __module__ = 'tetris_pb2'
    # @@protoc_insertion_point(class_scope:tetris.ProgressUpdate.Progress)
    ))
  ,
  DESCRIPTOR = _PROGRESSUPDATE,
  __module__ = 'tetris_pb2'
  # @@protoc_insertion_point(class_scope:tetris.ProgressUpdate)
  ))
_sym_db.RegisterMessage(ProgressUpdate)
_sym_db.RegisterMessage(ProgressUpdate.Progress)


# @@protoc_insertion_point(module_scope)
